apache/felix-dev

- tools/maven-bundle-plugin/pom.xml
- tools/maven-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/BundlePlugin.java
We should update the versions of maven-archiver + plexus-utils in the maven-bundle-plugin to remove the CVEs:
plexus-archiver-2.8.1.jar (pkg:maven/org.codehaus.plexus/plexus-archiver@2.8.1, cpe:2.3aplexus-archiver_project:plexus-archiver:2.8.1:::::::) : CVE-2018-1002200
plexus-utils-3.0.10.jar (pkg:maven/org.codehaus.plexus/plexus-utils@3.0.10, cpe:2.3aplexus-utils_project:plexus-utils:3.0.10:::::::) : CVE-2017-1000487, Directory traversal in org.codehaus.plexus.util.Expand, Possible XML Injection
> FELIX-6193 - Update maven-archiver + plexus-utils

- converter/converter/src/main/java/org/osgi/util/converter/ConvertingImpl.java
- converter/converter/src/test/java/org/osgi/util/converter/ConverterTest.java
- converter/converter/src/test/java/org/osgi/util/converter/InterfaceWithDefaultMethod.java
https://issues.apache.org/jira/browse/FELIX-6239
Default methods in interfaces exist since Java 8.
I did not found ONE way to invoke them.
I check the Java-Version and handles 2 different ways.
Maybe i should add an try-catch block do handle exceptions?
> [converter] handle default methods - FELIX-6239

- scr/src/main/java/org/apache/felix/scr/impl/BundleComponentActivator.java
- scr/src/main/java/org/apache/felix/scr/impl/manager/DependencyManager.java
- scr/src/main/java/org/apache/felix/scr/impl/manager/ExtendedServiceListenerContext.java
- scr/src/main/java/org/apache/felix/scr/impl/manager/ServiceTracker.java
- scr/src/test/java/org/apache/felix/scr/impl/manager/SingleComponentManagerTest.java
- scr/src/test/java/org/apache/felix/scr/integration/Felix6161Test.java
- scr/src/test/resources/integration_test_FELIX_6161.xml
This PR contains the patch already attached to FELIX-6161, but now applied on the current state of the felix-dev repository.
> [FELIX-6161] Replace local filtering of references in favour of relying on filtered ServiceListener callbacks

- scr/src/main/appended-resources/META-INF/DEPENDENCIES
- scr/src/main/appended-resources/META-INF/LICENSE
FELIX-6218 removed kxml from packaging, but did not update DEPENDENCIES and LICENSE. This patch finishes that up.
> [FELIX-6218] Remove kxml notice

- framework/src/main/java/org/apache/felix/framework/util/MultiReleaseContent.java
add try-with-resources to close InputStream that's otherwise leaked.
> [FELIX-6297] MultiReleaseContent leaks manifest InputStream

- scr/src/main/java/org/apache/felix/scr/impl/manager/DependencyManager.java
- scr/src/test/java/org/apache/felix/scr/integration/ServiceBindGreedyTest.java
- scr/src/test/java/org/apache/felix/scr/integration/components/felix3680_2/Main.java
If multiple threads register higher ranked services than
the currently bound service then a single thread is
selected to do the work of binding the highest ranked
service. The other threads just queue up the possible
service to be bound by the winning thread.
This ensures that the component will not
get out of order bindings for the various service
registration when a component has a dynamic, greedy reference
with cardinality of 0..1 or 1..1
A new testcase is added that registers 100 services with
different ranks using 10 threads. The test then confirms
that the highest ranked service is the current one bound
to the component. Theoretically the test could pass before
this fix, but multiple runs without the fix never resulted
in a passing test.
> FELIX-6317 - Ensure the order of dynamic binding follows service rank

- scr/src/main/java/org/apache/felix/scr/impl/Activator.java
- scr/src/main/java/org/apache/felix/scr/impl/config/ScrConfigurationImpl.java
- scr/src/main/java/org/apache/felix/scr/impl/logger/ExtLogManager.java
- scr/src/main/java/org/apache/felix/scr/impl/logger/LogManager.java
- scr/src/main/java/org/apache/felix/scr/impl/logger/ScrLogManager.java
- scr/src/test/java/org/apache/felix/scr/impl/logger/LoggerTest.java
Replacing the existing LogManager with a new one on
configuration updates causes the existing loggers for
each component to stop working properly.  This is a quick
fix to avoid creating a new LogManager on config updates
of SCR.  If dynamic updates is needed for the ds.log.extension
property then more work is needed.  For now this is a
one time setting only configured through context properties
> FELIX-6321 - keep existing LogManager on config update

- http/jetty/pom.xml
- http/jetty/src/main/java/org/apache/felix/http/jetty/internal/ConfigMetaTypeProvider.java
- http/jetty/src/main/java/org/apache/felix/http/jetty/internal/JettyConfig.java
- http/jetty/src/main/java/org/apache/felix/http/jetty/internal/JettyService.java
Please consider accepting these changes to enable HTTP/2 support in jetty.
> FELIX-5311 Allow Usage of HTTP/2 with Jetty Felix Http Service

- scr/src/main/java/org/apache/felix/scr/impl/logger/LogManager.java
- scr/src/main/java/org/apache/felix/scr/impl/logger/ScrLogManager.java
- scr/src/test/java/org/apache/felix/scr/impl/logger/LoggerTest.java
- scr/src/test/java/org/apache/felix/scr/integration/ComponentTestBase.java
- scr/src/test/java/org/apache/felix/scr/integration/Felix6325OptionalLogTest.java
Make the log package optional again.
The implementation still will only use
an OSGi R7 log service implementation
if one is available.
> FELIX-6325 - OSGi log package is mandatory but imported as optional

- scr/src/main/java/org/apache/felix/scr/impl/manager/SingleComponentManager.java
Reaching zero reference count for a component configuration created
via a component factory should not trigger that configuration being
deactivated.
> FELIX-6315: do not deactivate factory component configurations

- webconsole/src/main/java/org/apache/felix/webconsole/SimpleWebConsolePlugin.java
- webconsole/src/main/java/org/apache/felix/webconsole/internal/i18n/ConsolePropertyResourceBundle.java
- webconsole/src/test/java/org/apache/felix/webconsole/internal/servlet/OsgiManagerTest.java
Please consider this as a solution for FELIX-6341
> FELIX-6341 ConfigAdmin - deleting a configuration logs a string that should be translated

- fileinstall/src/main/java/org/apache/felix/fileinstall/internal/Watcher.java
An OVERFLOW event might have a context that is null. As a consequence the Path.resolve call will throw a null pointer exception
See https://issues.apache.org/jira/browse/FELIX-6338
> [FELIX-6338] Prevent Null pointer exception in fileinstall watcher

- scr/src/main/java/org/apache/felix/scr/impl/Activator.java
- scr/src/main/java/org/apache/felix/scr/impl/config/ScrConfigurationImpl.java
- scr/src/main/java/org/apache/felix/scr/impl/logger/ExtLogManager.java
- scr/src/main/java/org/apache/felix/scr/impl/logger/LogConfiguration.java
- scr/src/main/java/org/apache/felix/scr/impl/logger/LogManager.java
- scr/src/main/java/org/apache/felix/scr/impl/logger/NoOpLogger.java
- scr/src/main/java/org/apache/felix/scr/impl/logger/ScrLogManager.java
- scr/src/main/java/org/apache/felix/scr/impl/logger/ScrLoggerFactory.java
- scr/src/main/java/org/apache/felix/scr/impl/manager/ScrConfiguration.java
- scr/src/test/java/org/apache/felix/scr/impl/logger/LoggerTest.java
1. Fixed Problem with Log Extension
2. Introduced functionality to disable logging
Fixes [FELIX-6407](https://issues.apache.org/jira/browse/FELIX-6407)
> [FELIX-6407] SCR Logging Fixes and Improvements

- scr/src/main/java/org/apache/felix/scr/impl/inject/field/FieldHandler.java
- scr/src/main/java/org/apache/felix/scr/impl/manager/ComponentContextImpl.java
The problem occurred when multiple injected services tried to be removed from the component's injection. It is highly likely because of the usage of `TreeMap` in such concurrent environment. Since `TreeMap` has never been written to be used in a concurrent environment, we should use `ConcurrentSkipListMap` instead as all the features of `TreeMap` have been introduced in `ConcurrentSkipListMap` and it is very much suitable for concurrent environment.
> Introduced thread-safety while updating field during deactivation phase

- webconsole/src/main/java/org/apache/felix/webconsole/internal/configuration/ConfigManager.java
services returned from the spiTracker may be null
> FELIX-6367 add null check

- features/src/main/java/org/apache/felix/feature/impl/ArtifactBuilderImpl.java
- features/src/main/java/org/apache/felix/feature/impl/BundleBuilderImpl.java
This fixes a number of TCK failures
> Additional parameter checking

- healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/executor/HealthCheckResultCache.java
- healthcheck/core/src/test/java/org/apache/felix/hc/core/impl/executor/HealthCheckResultCacheTest.java
Use alternative constructor instead of spy.
Use local mock of  Servicereference.
> FELIX-6474 - Improve HealthCheckResultCacheTest

- tools/org.apache.felix.scr.generator/pom.xml
Upgrade asm lib to support Java 17.
Currently compiling a project in Java 17 with maven-src-plugin throw an exception:
Unable to scan class files: org.test.Test (Class file format probably not supported by ASM ?): Unsupported class file major version 61
> [FELIX-6489] ASM - support for Java 18

- scr/src/main/java/org/apache/felix/scr/impl/Activator.java
- scr/src/main/java/org/apache/felix/scr/impl/ComponentRegistry.java
Cancel the `changeCountTimer`. Also name its thread "SCR Component Registry" rather than leaving it as "Timer-0".
> FELIX-6511: Cancel the SCR Component Registry's changeCountTimer on deactivation.

- tools/maven-bundle-plugin/pom.xml
https://issues.apache.org/jira/browse/FELIX-6496
non-reproducible order of Exports/Imports https://github.com/bndtools/bnd/issues/5021 has been fixed
> [FELIX-6494] upgrade bndlib from 5.1.1 to 6.2.0

- tools/maven-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/ManifestPlugin.java
This PR addresses issue [FELIX-6493](https://issues.apache.org/jira/browse/FELIX-6493) and extends the is-up-to-date logic of the Manifest goal to
- consider as not up-to-date if the MANIFEST.MF file to generate does not exist
- consider pom.xml modifications in up-to-date logic
- write incremental-info after manifest to not self-cause out-of-date
> [FELIX-6493] Extend is-up-to-date logic of Manifest goal

- tools/maven-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/ManifestPlugin.java
This PR should fix [FELIX-6526](https://issues.apache.org/jira/browse/FELIX-6526) and [FELIX-6527](https://issues.apache.org/jira/browse/FELIX-6527).
The case that that the incremental manifest data file does not existing in regular, non-incremental builds was forgotten here and no unit-test for `ManifestPlugin` exists that could have detect that.
> FELIX-6526|FELIX-6527 Handle absent incremental manifest data file

- framework/src/main/java/org/apache/felix/framework/BundleWiringImpl.java
- presumption: such capability can be removed as impliesDirect would return false too.
> FELIX-6522 Empty name is not allowed in permissions.

- healthcheck/generalchecks/src/main/java/org/apache/felix/hc/generalchecks/BundlesStartedCheck.java
- healthcheck/generalchecks/src/test/java/org/apache/felix/hc/generalchecks/BundlesStartedCheckTest.java
making bundleStartedCheck to return TEMPORARILY_UNAVAILABLE instead of WARN to make it consistent with other health checks
> FELIX-6523 BundlesStartedCheck status is not aligned with other configs in the General HC

- healthcheck/generalchecks/src/main/java/org/apache/felix/hc/generalchecks/HttpRequestsCheck.java
- healthcheck/generalchecks/src/test/java/org/apache/felix/hc/generalchecks/HttpRequestsCheckTest.java
Enhance HttpRequestsCheck to handle http response code constraint checks. Currently only equality checks are supported for http response code checks, this PR introduces support for simple constraint checks for response code.
For example:
- /path/example.html => CODE < 500
- /path/example.html => CODE = 200
> [FELIX-6545] HttpRequestsCheck add support for http response code constraint checks

- healthcheck/generalchecks/src/main/java/org/apache/felix/hc/generalchecks/ScriptedHealthCheck.java
- healthcheck/generalchecks/src/main/java/org/apache/felix/hc/generalchecks/util/ScriptEnginesTracker.java
- healthcheck/generalchecks/src/test/java/org/apache/felix/hc/generalchecks/util/DummyScriptEngineFactory.java
- healthcheck/generalchecks/src/test/java/org/apache/felix/hc/generalchecks/util/ScriptEnginesTrackerTest.java
The ScriptEnginesTracker in the Felix Health Check General Checks should handle loading of ScriptEngineFactory serviceloader (/META-INF/services/javax.script.ScriptEngineFactory) files that exist in a fragment.
For example, consider the groovy ScriptEngine that has these:
Host Bundle - org.codehaus.groovy:groovy:3.0.9
Fragment - org.codehaus.groovy:groovy-jsr223:3.0.9
Expected:
The groovy ScriptEngineFactory declared in the groovy-jsr223 fragment should be discovered and made available.
> FELIX-6542 ScriptedHealthCheck should handle ScriptEngineFactory defined in a fragment bundle

- tools/maven-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/ManifestWriter.java
Extend the list of nicely formatted headers by the `manifest` goal by the following elements:
- `Require-Bundle`
- `Bundle-ClassPath`
- `Embedded-Artifacts`
And apply some minor code/comment improvements.
> [FELIX-6491] Extend List of niceManifest headers

- metatype/src/main/java/org/apache/felix/metatype/AD.java
OSGi Compendium 7.0.0, 105.14.2.18 and 105.14.2.19 specify that if the
function returns null, there are no option values or labels available.
Currently, these get set to String[0] because the options map.size()
returns 0.
> [FELIX-6332] AttributeDefinition options should return null when not present

- tools/maven-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/BundlePlugin.java
fixes https://issues.apache.org/jira/browse/FELIX-6602
tested on a few projects (mybatis-3, activemq-artemis), using disorderfs to make sure that these 2 changes fix last remaining issues
> FELIX-6602 sort resources and exported packages

- webconsole/src/main/java/org/apache/felix/webconsole/internal/configuration/ConfigAdminSupport.java
- webconsole/src/main/resources/res/ui/config.js
This pull request addresses the issue of an empty value being saved when a list property has no value (FELIX-6614). The proposed solution is to filter out the request query parameters that have empty values.
> FELIX-6614 WebConsole configMgr saves an empty value in list properites

- scr/src/main/java/org/apache/felix/scr/impl/manager/DependencyManager.java
- scr/src/test/java/org/apache/felix/scr/integration/ConfigurationChangeTest.java
- scr/src/test/resources/integration_test_simple_components_configuration_change.xml
Ensure no new add events got missed when deactivating on removed service
This change follows the same pattern as other reference types but also does it for dynamic references when they become unsatisfied.
The fix is to simply cause the dependency manager to be checked again after the removed event gets processed to ensure the dependency is not now satisfied.
> FELIX-6633 : Dynamic references may miss events while causing deactivation

- http/jetty12/pom.xml
- http/samples/whiteboard/pom.xml
- http/samples/whiteboard/src/main/java/org/apache/felix/http/samples/whiteboard/Activator.java
- http/samples/whiteboard/src/main/java/org/apache/felix/http/samples/whiteboard/FelixJettyWebSocketServlet.java
- http/samples/whiteboard/src/main/java/org/apache/felix/http/samples/whiteboard/TestWebSocketServlet.java
This change makes it possible to use [Jetty WebSocket](https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-server-websocket-jetty) (not JakartaEE 10) functionality via the Felix HTTP Jetty 12 bundle.
There are still some strange things that need to be done when writing a WebSocket servlet to get it all to work, but that's for a separate change request/bug report. I requested access to the Felix Jira so i can add it to the jira project.
More info about the required changes needed for setting up an actual websocket servlet. I combined the solutions mentioned in the links below (change classloader, delayed init and Jetty container websocket initialization code), otherwise the Websocket servlet fails to be initialized. 
* …
> Add jetty websocket support to Jetty12 

- http/README.md
Update the HTTP documentation to reference the example code.
> Add reference to the WebSocket example code

- http/README.md
- http/jetty12/src/main/java/org/apache/felix/http/jetty/internal/ConfigMetaTypeProvider.java
- http/jetty12/src/main/java/org/apache/felix/http/jetty/internal/JettyConfig.java
- http/jetty12/src/main/java/org/apache/felix/http/jetty/internal/JettyService.java
See https://issues.apache.org/jira/browse/FELIX-6698
- Add `org.eclipse.jetty.UriComplianceMode` option
- Possible values are: `DEFAULT`, `LEGACY`, `RFC3986`, `UNAMBIGUOUS`, `UNSAFE`
- `DEFAULT` and `RFC3986` are equivalent. Jetty uses `DEFAULT` as default, which is equivalent to `RFC3986`.
- When `UNSAFE`, `UNAMBIGUOUS` or `LEGACY` is used, also apply workaround as suggested in https://github.com/jetty/jetty.project/issues/11448#issuecomment-1969206031. This is not Servlet API 6 compliant though, so use on your own risk.
More info about the possible modes: https://github.com/jetty/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-http/src/main/java/org/eclipse/jetty/http/UriCompliance.java
@cziegeler sorry to bother you again, but i have another request ready.
> FELIX-6698 Ability to configure URI Compliance mode

- scr/changelog.txt
- scr/src/main/java/org/apache/felix/scr/impl/BundleComponentActivator.java
When a bundle's Service-Component header contains explicit paths and wildcard paths, it is possible for an explicit descriptor entry to be parsed twice, if it is also matched by a wildcard entry. This results in an ERROR level log similar to that described in [FELIX-2325](https://issues.apache.org/jira/browse/FELIX-2325). The use case which requires this mix of wildcard and non-wildcard entries is probably rare, but such is the situation with https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3241
In this situation, bnd is used to package the host bundle, and so the descriptors for the DS components contained within it are listed explicitly in the Service-Component header value generated by the bnd tool. 
Additionally, the project packages some optional component …
> FELIX-6699 Skip parsing of repeated Service-Component entries

- http/jetty/pom.xml
- http/jetty/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java
- http/jetty/src/test/java/org/apache/felix/http/jetty/it/LightClassifierIT.java
- http/jetty12/pom.xml
- http/jetty12/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java
- http/jetty12/src/test/java/org/apache/felix/http/jetty/it/LightClassifierIT.java
The "light" classifier doesn't export the following packages.  These packages were present in the jar but as a private package.
`org.osgi.service.servlet.context;version="2.0.0";uses:="jakarta.servlet.http,org.osgi.framework"
org.osgi.service.servlet.runtime.dto;version="2.0.0";uses:="org.osgi.dto,org.osgi.framework.dto"
org.osgi.service.servlet.runtime;version="2.0.0";uses:="org.osgi.service.servlet.runtime.dto"
org.osgi.service.servlet.whiteboard;version="2.0.0";uses:="jakarta.servlet"`
This proposal changes those private packages to be exported packages.  Also an integration test is added to verify the functionality.
This ensures that any other bundles that import those packages (i.e. the felix webconsole 5.x) will resolve.
For example, without these changes I get these errors:
``` …
```
> FELIX-6700 Missing o.o.service.servlet.* export-package in felix jetty

- .github/workflows/maven.yml
This adds a github verification workflow for the scr component of felix dev.
I created an example PR how it would looks like after the merge here:
- https://github.com/laeubi/felix-dev/pull/3
FYI @tjwatson @stbischof  I think this should be merged first as it does not require any changes to the code itself to make it run, once we have this we can rebase
- https://github.com/apache/felix-dev/pull/320
- https://github.com/apache/felix-dev/pull/301
on this and further enhance it.
> Add github verification for SCR

- http/jetty/pom.xml
- http/jetty/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java
- http/jetty12/pom.xml
- http/jetty12/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java
- http/samples/whiteboard/pom.xml
See https://issues.apache.org/jira/browse/FELIX-6725
- Upgrade Jetty 11 and 12 to latest
> FELIX-6725 Update to Jetty 12.0.13 / 11.0.24

- fileinstall/pom.xml
Due to bug in older version of felix-utils fileinstall can't handle all variants of typed properties properly, especially (a, b, c) syntax..
> FELIX-6687 Fix handling of typed properties in felix fileinstall

- pom/pom.xml
https://issues.apache.org/jira/browse/FELIX-6744
- Configure OddEvenVersionPolicy based on the undocumented rule of having even version number for releases, and odd versions for development
> FELIX-6744 Configure policy for maven release plugin

- http/base/src/main/java/org/apache/felix/http/base/internal/dispatch/Dispatcher.java
- http/base/src/main/java/org/apache/felix/http/base/internal/dispatch/RequestDispatcherImpl.java
- http/base/src/main/java/org/apache/felix/http/base/internal/dispatch/ServletRequestMultipartWrapper.java
- http/base/src/main/java/org/apache/felix/http/base/internal/dispatch/ServletRequestWrapper.java
- http/base/src/main/java/org/apache/felix/http/base/internal/dispatch/ServletResponseWrapper.java
Mostly in the usage of felix-jetty-light there is the cases where you do not need the multipart support and can remove the dependencies of common-fileupload and common-io. To be able to do this we could not load a instantiate a class that imports common-fileupload classes. So we have to free the old class ServletRequestWrapper of this imports and add a ServletRequestMultipartWrapper that still have the multipart support.
> [http] extract Multipart code into new ServletRequestMultipartWrapper

- .github/workflows/maven-ci.yml
- log/pom.xml
- log/src/main/java/org/apache/felix/log/Activator.java
- log/src/main/java/org/apache/felix/log/FormatterLoggerImpl.java
- log/src/main/java/org/apache/felix/log/Log.java
- log/src/main/java/org/apache/felix/log/LogEntryImpl.java
- log/src/main/java/org/apache/felix/log/LogListenerThread.java
- log/src/main/java/org/apache/felix/log/LogNodeEnumeration.java
- log/src/main/java/org/apache/felix/log/LogReaderServiceFactory.java
- log/src/main/java/org/apache/felix/log/LogReaderServiceImpl.java
- log/src/main/java/org/apache/felix/log/LogServiceFactory.java
- log/src/main/java/org/apache/felix/log/LogServiceImpl.java
- log/src/main/java/org/apache/felix/log/LoggerAdminImpl.java
- log/src/main/java/org/apache/felix/log/LoggerContextImpl.java
- log/src/main/java/org/apache/felix/log/RootLoggerContextImpl.java
- pom/pom.xml
- scr/src/main/java/org/apache/felix/scr/impl/ComponentCommands.java
While I was working on reviving felix.logback I was going through the code and I wondered if it could be modernized a little bit. This is the result. I am not sure if it is useful for the project as I have no idea what minimum platform and JVM version it targets.
> Use OSGi Annotations to produce felix.log manifest and clean up.

- scr/src/main/java/org/apache/felix/scr/impl/BundleComponentActivator.java
Currently SCR prints an error if one uses a wildcard in the header but nothing matches. But because fragemnts are not allowed to provide an own header, only the host can enable this.
So this now adds an additional check before logging an error that prevents an error from being printed if a wildcard is provided.
See
- https://github.com/osgi/osgi/issues/789
- https://github.com/eclipse-platform/.github/issues/241
- https://github.com/eclipse-lemminx/lemminx/pull/1732
> Do not print an error when a wildcard is used in component header

- http/jetty/pom.xml
This PR updates the version of jetty to latest available 9.4.x version.
> FELIX-6760 - Update to Jetty 9.4.57.v20241219 on http-4.x

- .github/workflows/maven-ci.yml
- framework/doc/changelog.txt
- framework/pom.xml
- ci job
- update mockito-core to mockito to latest version to run on java 17 and not only 8
- update felix-parent version to avoid build issue with `org.codehaus.mojo:ianal-maven-plugin:1.0-alpha-1`
> [FELIX-6765] - Add a CI-job for Felix Framework

- http/jetty12/src/test/java/org/apache/felix/http/jetty/it/JettyMaxFormSizeIT.java
- http/jetty12/src/test/java/org/apache/felix/http/jetty/it/JettyUriComplianceModeDefaultIT.java
- http/jetty12/src/test/java/org/apache/felix/http/jetty/it/JettyUriComplianceModeLegacyIT.java
- Add integration test for demonstrating the issue
> FELIX-6774 `org.apache.felix.http.jetty.maxFormSize` not enforced: Unit test to demonstrate issue

- scr/pom.xml
- scr/src/test/java/org/apache/felix/scr/integration/ComponentTestBase.java
- scr/src/test/resources/exam.properties
- scr/src/test/resources/logback-test.xml
Related to PR #420, on getting control on the logging. This changes disables Pax Exam's preference for Pax Logging, and changes it with Logback (in the latest SLF4j 1.7.x compatible version). With this change, SLF4j and Logback are now available for both the unit tests and the pax exam tests.
Configured explicit versions of all 'mavenBundle's declared in the ComponentTestBase, as otherwise Pax will depend on Maven's LATEST, which is not always compatible. By using fixed versions (compatible with what is in the pom file), I also fixed test Felix6274Test, that I noticed failing (both on master and in #419)
> Replace Pax Logging with Logback in Pax Exam tests
