converter/converter/src/main/java/org/osgi/util/converter/ConvertingImpl.java, converter/converter/src/test/java/org/osgi/util/converter/ConverterTest.java
https://issues.apache.org/jira/browse/FELIX-6238
=> Convert to Interface without methods - FELIX-6238

scr/src/main/java/org/apache/felix/scr/impl/manager/DependencyManager.java
Need to ensure the tracker is not null.  Also calls to tracked can
return null and need to be handled without an NPE
=> FELIX-6251 - Fix NPE in DependencyManager for references to m_tracker

healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/executor/HealthCheckExecutorImpl.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/executor/HealthCheckExecutorThreadPool.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/executor/async/AsyncHealthCheckExecutor.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/monitor/HealthCheckMonitor.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/CronSchedulerProviderEnabler.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/HealthCheckCronScheduler.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/embedded/AsyncEmbeddedCronJob.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/embedded/EmbeddedCronJob.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/embedded/EmbeddedCronParser.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/embedded/EmbeddedCronScheduler.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/embedded/EmbeddedCronSchedulerProvider.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/embedded/EmbeddedCronSchedulerTask.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/quartz/AsyncQuartzCronJob.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/quartz/CronJobFactory.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/quartz/QuartzCronScheduler.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/scheduling/cron/quartz/QuartzCronSchedulerProvider.java, healthcheck/core/src/test/java/org/apache/felix/hc/core/impl/scheduling/cron/embedded/EmbeddedCronParserTest.java, healthcheck/core/src/test/java/org/apache/felix/hc/core/impl/scheduling/cron/embedded/EmbeddedCronSchedulerTest.java, healthcheck/core/src/test/java/org/apache/felix/hc/core/impl/scheduling/cron/embedded/EmbeddedCronTriggerTest.java, healthcheck/core/src/test/java/org/apache/felix/hc/core/impl/scheduling/cron/embedded/EmbeddedSampleCronJob1.java, healthcheck/core/src/test/java/org/apache/felix/hc/core/impl/scheduling/cron/embedded/EmbeddedSampleCronJob2.java
Fixed https://issues.apache.org/jira/browse/FELIX-6265
Signed-off-by: Amit Kumar Mondal <admin@amitinside.com>
=> [FELIX-6265] Introduced Embedded Cron Scheduler

README.md, metrics/osgi/README.md, metrics/osgi/collector/bnd.bnd, metrics/osgi/collector/pom.xml, metrics/osgi/collector/src/main/java/org/apache/felix/metrics/osgi/BundleStartDuration.java, metrics/osgi/collector/src/main/java/org/apache/felix/metrics/osgi/ServiceRestartCounter.java, metrics/osgi/collector/src/main/java/org/apache/felix/metrics/osgi/StartupMetrics.java, metrics/osgi/collector/src/main/java/org/apache/felix/metrics/osgi/StartupMetricsListener.java, metrics/osgi/collector/src/main/java/org/apache/felix/metrics/osgi/impl/Activator.java, metrics/osgi/collector/src/main/java/org/apache/felix/metrics/osgi/impl/BundleStartTimeCalculator.java, metrics/osgi/collector/src/main/java/org/apache/felix/metrics/osgi/impl/Log.java, metrics/osgi/collector/src/main/java/org/apache/felix/metrics/osgi/impl/ServiceRestartCountCalculator.java, metrics/osgi/collector/src/main/java/org/apache/felix/metrics/osgi/impl/ServiceTrackerCustomizerAdapter.java, metrics/osgi/collector/src/main/java/org/apache/felix/metrics/osgi/impl/StartupTimeCalculator.java, metrics/osgi/collector/src/main/java/org/apache/felix/metrics/osgi/package-info.java, metrics/osgi/collector/src/test/java/org/apache/felix/metrics/osgi/impl/AbstractIT.java, metrics/osgi/collector/src/test/java/org/apache/felix/metrics/osgi/impl/BundleStartTimeCalculatorTest.java, metrics/osgi/collector/src/test/java/org/apache/felix/metrics/osgi/impl/HealthCheckSmokeIT.java, metrics/osgi/collector/src/test/java/org/apache/felix/metrics/osgi/impl/ServiceRegistrationsTrackerTest.java, metrics/osgi/collector/src/test/java/org/apache/felix/metrics/osgi/impl/ServiceRestartCountCalculatorTest.java, metrics/osgi/collector/src/test/java/org/apache/felix/metrics/osgi/impl/SystemReadySmokeIT.java, metrics/osgi/collector/src/test/java/org/apache/felix/metrics/osgi/impl/WaitForResultsStartupMetricsListener.java, metrics/osgi/consumers/bnd.bnd, metrics/osgi/consumers/pom.xml, metrics/osgi/consumers/src/main/java/org/apache/felix/metrics/osgi/consumers/impl/dropwizard/DropwizardMetricsListener.java, metrics/osgi/consumers/src/main/java/org/apache/felix/metrics/osgi/consumers/impl/json/JsonWritingMetricsListener.java, metrics/osgi/consumers/src/main/java/org/apache/felix/metrics/osgi/consumers/impl/log/LoggingMetricsListener.java, metrics/osgi/consumers/src/test/java/org/apache/felix/metrics/osgi/consumers/impl/json/JsonWritingMetricsListenerTest.java, metrics/osgi/pom.xml
See https://lists.apache.org/thread.html/rd3b9769a3263eddad829a1494d6ec73cbe041bcd74a77c7f9c9c9af7%40%3Cdev.felix.apache.org%3E
=> Contribute OSGi metrics modules

configadmin-plugins/interpolation/README.md, configadmin-plugins/interpolation/src/main/java/org/apache/felix/configadmin/plugin/interpolation/Interpolator.java, configadmin-plugins/interpolation/src/test/java/org/apache/felix/configadmin/plugin/interpolation/InterpolationConfigurationPluginTest.java
In addition support "=" within directive values
=> FELIX-6384 support empty directive values

http/servlet-api/pom.xml
https://issues.apache.org/jira/browse/FELIX-6426
=> Felix 6426 update tomcat dependency to the latest 8.x version

configadmin-plugins/interpolation/src/main/java/org/apache/felix/configadmin/plugin/interpolation/StandaloneInterpolator.java, configadmin-plugins/interpolation/src/test/java/org/apache/felix/configadmin/plugin/interpolation/StandaloneInterpolatorTest.java
Prevent NPE when null passed in for secrets locations
=> FELIX-6441 Make it possible to run the Configuration Interpolation independently of Configuration Admin

features/pom.xml, features/src/main/java/org/apache/felix/feature/impl/ArtifactBuilderImpl.java, features/src/main/java/org/apache/felix/feature/impl/BuilderFactoryImpl.java, features/src/main/java/org/apache/felix/feature/impl/BundleBuilderImpl.java, features/src/main/java/org/apache/felix/feature/impl/ConfigurationBuilderImpl.java, features/src/main/java/org/apache/felix/feature/impl/ExtensionBuilderImpl.java, features/src/main/java/org/apache/felix/feature/impl/FeatureBuilderImpl.java, features/src/main/java/org/apache/felix/feature/impl/FeatureServiceImpl.java, features/src/main/java/org/apache/felix/feature/impl/IDImpl.java, features/src/test/java/org/apache/felix/feature/impl/FeatureServiceImplTest.java, features/src/test/resources/features/test-exfeat1.json, features/src/test/resources/features/test-exfeat2.json, features/src/test/resources/features/test-feature.json, features/src/test/resources/features/test-feature2.json
As discussed at the Felix Mailing list: https://www.mail-archive.com/dev%40felix.apache.org/msg52338.html
This implementation was initially made in the Apache Sling Whiteboard component at
https://github.com/apache/sling-whiteboard/tree/master/osgi-featuremodel
=> FELIX-6444 Contribute a compatible implementation of OSGi Features

features/src/main/java/org/apache/felix/feature/impl/ArtifactBuilderImpl.java
Signed-off-by: Stefan Bischof <stbischof@bipolis.org>
=> Features - fix typo in Exception-message

features/src/main/java/org/apache/felix/feature/impl/ArtifactBuilderImpl.java, features/src/main/java/org/apache/felix/feature/impl/BundleBuilderImpl.java
Signed-off-by: Stefan Bischof <stbischof@bipolis.org>
=> Feature - Fix type in Exception-message (2)

scr/pom.xml, scr/src/main/java/org/apache/felix/scr/impl/runtime/ServiceComponentRuntimeImpl.java, scr/src/test/java/org/apache/felix/scr/impl/runtime/ServiceComponentRuntimeImplTest.java
> Use ServiceReference.adaptTo(ServiceReferenceDTO)
=> FELIX-6458 : Use ServiceReference.adaptTo(ServiceReferenceDTO)

webconsole/src/main/resources/res/ui/config.css, webconsole/src/main/resources/res/ui/config.js
allows to disambiguate multiple designates pointing to the same OCD
=> FELIX-6040 expose PID in ConfigMgr WebConsole

examples/extenderbased.host/pom.xml, examples/extenderbased.host/src/main/java/org/apache/felix/example/extenderbased/host/ShapeBundleTracker.java, examples/extenderbased.host/src/main/java/org/apache/felix/example/extenderbased/host/extension/SimpleShape.java, examples/extenderbased.square/pom.xml, examples/servicebased.circle/src/main/java/org/apache/felix/example/servicebased/circle/Activator.java, examples/servicebased.host/src/main/java/org/apache/felix/example/servicebased/host/DefaultShape.java, examples/servicebased.host/src/main/java/org/apache/felix/example/servicebased/host/ShapeTracker.java, examples/servicebased.host/src/main/java/org/apache/felix/example/servicebased/host/service/SimpleShape.java
I was doing the Felix tutorials and noticed that the sample projects didn't work, so this PR fixes them.
=> Fix service-based and extender-based sample projects

tools/maven-bundle-plugin/pom.xml, tools/maven-bundle-plugin/src/it/archiver/pom.xml, tools/maven-bundle-plugin/src/it/archiver/verify.groovy, tools/maven-bundle-plugin/src/it/reproducible/pom.xml, tools/maven-bundle-plugin/src/it/reproducible/verify.groovy, tools/maven-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/BundlePlugin.java
this time, I added ITs to avoid the 2 previous regressions
see https://issues.apache.org/jira/browse/FELIX-6404
=> [FELIX-6404] fix Reproducible Builds support

healthcheck/core/pom.xml
see https://maven.apache.org/pom/asf/
=> add local reproducible build timestamp

pom/pom.xml
see https://maven.apache.org/pom/asf/
=> add local timestamp for Reproducible Build

tools/maven-bundle-plugin/pom.xml
https://issues.apache.org/jira/browse/FELIX-6471
=> [FELIX-6471] make build reproducible

scr/src/main/java/org/apache/felix/scr/impl/manager/ComponentContextImpl.java
Fixes [FELIX-6501](https://issues.apache.org/jira/browse/FELIX-6501)
=> [FELIX-6501] Fixed issue with ConcurrentModificationException

configadmin/src/main/java/org/apache/felix/cm/impl/ConfigurationManager.java
Signed-off-by: Raymond Augé <rotty3000@apache.org>
=> FELIX-6514 NPE on ConfigurationEvent

configadmin-plugins/interpolation/README.md, configadmin-plugins/interpolation/src/main/java/org/apache/felix/configadmin/plugin/interpolation/InterpolationConfigurationPlugin.java, configadmin-plugins/interpolation/src/test/java/org/apache/felix/configadmin/plugin/interpolation/InterpolationConfigurationPluginTest.java
Signed-off-by: Raymond Augé <rotty3000@apache.org>
=> FELIX-6518 - Enable interpolation plugin to self reference properties

framework/src/main/java/org/apache/felix/framework/FrameworkStartLevelImpl.java
Remove the synchronization on Integer and replace it with a dedicated StartLevelRequest object
=> FELIX-6516 - Remove synchronization on Integer

scr/src/main/java/org/apache/felix/scr/impl/runtime/ServiceComponentRuntimeImpl.java
Fixes https://issues.apache.org/jira/browse/FELIX-6564
=> [FELIX-6564] Fixed NPE while retrieving component descriptions from SCR

gogo/runtime/src/main/java/org/apache/felix/gogo/runtime/Reflective.java
When using reflection to invoke a method on an object, the Reflective object only considers the method on the class. If the class is a non public class (such as a private implementation of a public interface), the new access rules make it impossible to use.
The proposal is to go through methods of public interfaces / classes first.
See https://issues.apache.org/jira/browse/FELIX-6597
=> [FELIX-6597] IllegalAccess when using reflection on public methods

framework.security/src/main/java/org/apache/felix/framework/SecurityActivator.java, framework.security/src/main/java/org/apache/felix/framework/security/util/Conditions.java, framework.security/src/main/java/org/apache/felix/framework/security/util/Permissions.java
Fix memory leak when bundles are uninstalled from the Felix framework:
- Fix the "`equals()` / `hashCode()`" contract for the `Permissions.Entry` class when the entry it is wrapping is an array.
- Remove `Conditions` objects explicitly when their bundles are uninstalled, instead of using `WeakHashMap`s.
=> FELIX-6591: Deallocate Conditions and Permissions when bundles unloaded.

framework/src/test/java/org/apache/felix/framework/FilterTest.java
I had a look an Filters because of FELIX-6335 and wrote this test.
Filters is NOT the Problem. So i have this test. 
Maybe you want to merge it as additional WORKING test.
=> Only a Test on Filter using Arrays

healthcheck/core/bnd.bnd, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/servlet/HealthCheckExecutorServlet.java, healthcheck/core/src/main/java/org/apache/felix/hc/core/impl/servlet/HealthCheckExecutorServletConfiguration.java, healthcheck/core/src/test/java/org/apache/felix/hc/core/impl/servlet/HealthCheckExecutorServletTest.java
fixes [FELIX-6565](https://issues.apache.org/jira/browse/FELIX-6565)
=> Updated to use HTTP optionally in HealthCheck

webconsole/src/main/java/org/apache/felix/webconsole/WebConsoleConstants.java, webconsole/src/main/java/org/apache/felix/webconsole/internal/servlet/OsgiManager.java, webconsole/src/main/java/org/apache/felix/webconsole/internal/system/VMStatPlugin.java, webconsole/src/main/resources/templates/vmstat.html, webconsole/src/main/resources/templates/vmstat_restart.html
JIRA REF: [FELIX-6356](https://issues.apache.org/jira/browse/FELIX-6356)
=> Introduce configuration options for setting felix shutdown and reload timeout

webconsole/src/main/java/org/apache/felix/webconsole/internal/configuration/ConfigurationUtil.java
- Replace square brackets with underscore characters that will make this URL-compliant.
=> FELIX-6629 Fix placeholder PID

webconsole/src/main/resources/res/ui/config.css
- Modified CSS styling to preserve newline characters in description to allow for nicer formatting
=> FELIX-6630 Allow newlines in description

http/jetty/pom.xml
This PR upgrades the version of jetty to 9.4.52.v20230823
=> FELIX-6648 - Update Jetty to 9.4.52.v20230823

scr/src/main/java/org/apache/felix/scr/impl/Activator.java
This fix detects the UNRESOLVED event in addition to the UPDATED and UNINSTALLED events to remove the meta-data cache for a bundle. Additionally, this fix detects cases where a fragment is resolved and dynamically attached to a host. In this case it also removes the host meta-data cache.
=> FELIX-6667 - Reresoliving hosts or resolving new fragments does not invalidate meta-data cache for SCR

scr/src/main/java/org/apache/felix/scr/impl/inject/field/FieldHandler.java, scr/src/main/java/org/apache/felix/scr/impl/inject/methods/BaseMethod.java, scr/src/main/java/org/apache/felix/scr/impl/manager/AbstractComponentManager.java, scr/src/main/java/org/apache/felix/scr/impl/manager/DependencyManager.java
Using TRACE for logs used solely for debugging felix's code and not the client's
=> FELIX-6463 : Changing log levels to trace

tools/osgicheck-maven-plugin/pom.xml, tools/osgicheck-maven-plugin/src/main/java/org/apache/felix/maven/osgicheck/impl/CheckContext.java, tools/osgicheck-maven-plugin/src/main/java/org/apache/felix/maven/osgicheck/impl/checks/ConsumerProviderTypeCheck.java
Supports bytecode scanning for Java up to version 22 Improve exception handling
=> FELIX-6660 - Update ASM to 9.6

http/jetty/src/main/java/org/apache/felix/http/jetty/internal/JettyService.java
Fix import for Jetty11 websockets.
@cziegeler
=> Fix import for Jetty11 websockets

http/jetty12/src/main/java/org/apache/felix/http/jetty/internal/JettyService.java, http/jetty12/src/test/java/org/apache/felix/http/jetty/it/JettyUriComplianceModeDefaultIT.java, http/jetty12/src/test/java/org/apache/felix/http/jetty/it/JettyUriComplianceModeLegacyIT.java
When making code review changes, an error was made in using the enum. This pr fixes it.
Will add a unit test to guard behavior.
https://issues.apache.org/jira/browse/FELIX-6698
=> Fix uriComplianceMode

webconsole/README.md
[FELIX-6703](https://issues.apache.org/jira/browse/FELIX-6703)
=> webconsole doc: add missing conf props

http/jetty/pom.xml, http/jetty/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java, http/jetty12/pom.xml, http/jetty12/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java, http/samples/whiteboard/pom.xml
See https://issues.apache.org/jira/browse/FELIX-6716
- Upgrade Jetty in both bundles
- 11.0.22 and 12.0.11
https://github.com/jetty/jetty.project/releases/tag/jetty-11.0.22
https://github.com/jetty/jetty.project/releases/tag/jetty-12.0.11
=> FELIX-6716 Update to Jetty 11.0.22 / 12.0.11

http/wrappers/src/main/java/org/apache/felix/http/jakartawrappers/FilterChainWrapper.java, http/wrappers/src/main/java/org/apache/felix/http/jakartawrappers/FilterConfigWrapper.java, http/wrappers/src/main/java/org/apache/felix/http/javaxwrappers/FilterWrapper.java
I added some warappers for the filters that are missing in the current implementation
=> Adds missing filter wrappers

http/jetty12/pom.xml, http/jetty12/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java, http/samples/whiteboard/pom.xml
https://issues.apache.org/jira/browse/FELIX-6728
=> FELIX-6728 Update to Jetty 12.0.14

http/jetty12/pom.xml, http/jetty12/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java, http/samples/whiteboard/pom.xml
=> FELIX-6734 Update to Jetty 12.0.15

configurator/src/main/java/org/apache/felix/configurator/impl/ServicesListener.java, dependencymanager/org.apache.felix.dependencymanager.itest/src/org/apache/felix/dm/itest/api/AspectRaceTest.java, dependencymanager/org.apache.felix.dependencymanager.itest/src/org/apache/felix/dm/itest/api/ServiceRaceTest.java, dependencymanager/org.apache.felix.dependencymanager.itest/src/org/apache/felix/dm/itest/api/ServiceRaceWithOrderedUnbindTest.java, gogo/jline/src/test/java/org/apache/felix/gogo/jline/telnet/ConnectionListener.java, ipojo/runtime/composite/src/main/java/org/apache/felix/ipojo/composite/instance/InstanceHandler.java, log/src/main/java/org/apache/felix/log/Activator.java, log/src/main/java/org/apache/felix/log/ConfigurationListenerImpl.java, log/src/main/java/org/apache/felix/log/Log.java, utils/src/main/java/org/apache/felix/utils/json/JSONParser.java
This fixes the "occured" misspelling of "occurred."
=> Fix spelling of occurred.

http/jetty12/pom.xml, http/jetty12/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java, http/samples/whiteboard/pom.xml
Draft until the release is out.
Also update wrappers to 1.1.8.
=> FELIX-6743 Update to Jetty 12.0.16

webconsole/src/main/java/org/apache/felix/webconsole/internal/servlet/OsgiManager.java
Stack trace of NPE in [FELIX-6747](https://issues.apache.org/jira/browse/FELIX-6747)
=> FELIX-6747 - NPE in activator of webconsole

.github/dependabot.yml
This will help keeping the GitHub Actions up to date.
=> Create dependabot.yml, allow update checks for GitHub Actions.

http/jetty12/pom.xml, http/jetty12/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java, http/samples/whiteboard/pom.xml
https://issues.apache.org/jira/browse/FELIX-6764
=> FELIX-6764 Update to Jetty 12.0.19

.github/workflows/maven-ci.yml, framework.tck/pom.xml, framework.tck/tck.bndrun
first commit could be ignored. ist PR #403
relevant is the 2. commit that showns running  OSGi-TCK osgi.test.cases.framework 
in actions you can see that framework is tck complient
https://issues.apache.org/jira/browse/FELIX-6766
=> [framework] add tck module - run the OSGi-TCK osgi.test.cases.framework 

.github/workflows/maven-ci.yml, framework.tck/.gitignore, framework/pom.xml
with jdk24 the missing SecurityManager will make the tests fail
=> [ci] matrix run on major versions and 23

http/jetty/pom.xml, http/jetty12/pom.xml, http/sslfilter/pom.xml, http/wrappers/pom.xml
=> FELIX-6780 Java 23 CI failure for HTTP Jetty RequestLogTrackerTest

http/base/pom.xml, http/jetty12/pom.xml, http/jetty12/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java, http/samples/whiteboard/pom.xml
https://issues.apache.org/jira/browse/FELIX-6788
=> FELIX-6788 Update to Jetty 12.0.22

http/base/pom.xml, http/jetty12/pom.xml, http/jetty12/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java, http/samples/whiteboard/pom.xml
https://issues.apache.org/jira/browse/FELIX-6790
- Upgrade to 12.0.23
=> FELIX-6790 Update to Jetty 12.0.23

http/base/pom.xml, http/itest/pom.xml, http/jetty12/pom.xml, http/jetty12/src/test/java/org/apache/felix/http/jetty/it/AbstractJettyTestSupport.java, http/samples/whiteboard/pom.xml
=> FELIX-6803 Update to Jetty 12.0.26
